# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reqresp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reqresp.proto',
  package='reqresp',
  serialized_pb=_b('\n\rreqresp.proto\x12\x07reqresp\"[\n\tCreateReq\x12\r\n\x05magic\x18\x01 \x02(\r\x12\n\n\x02op\x18\x02 \x02(\r\x12\x0c\n\x04opsn\x18\x03 \x02(\r\x12\x11\n\tvolume_id\x18\x04 \x02(\r\x12\x12\n\nchunk_size\x18\x05 \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CREATEREQ = _descriptor.Descriptor(
  name='CreateReq',
  full_name='reqresp.CreateReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='magic', full_name='reqresp.CreateReq.magic', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='op', full_name='reqresp.CreateReq.op', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='opsn', full_name='reqresp.CreateReq.opsn', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='volume_id', full_name='reqresp.CreateReq.volume_id', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chunk_size', full_name='reqresp.CreateReq.chunk_size', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['CreateReq'] = _CREATEREQ

CreateReq = _reflection.GeneratedProtocolMessageType('CreateReq', (_message.Message,), dict(
  DESCRIPTOR = _CREATEREQ,
  __module__ = 'reqresp_pb2'
  # @@protoc_insertion_point(class_scope:reqresp.CreateReq)
  ))
_sym_db.RegisterMessage(CreateReq)


# @@protoc_insertion_point(module_scope)
