// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reqresp.proto

#ifndef PROTOBUF_reqresp_2eproto__INCLUDED
#define PROTOBUF_reqresp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace reqresp {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_reqresp_2eproto();
void protobuf_AssignDesc_reqresp_2eproto();
void protobuf_ShutdownFile_reqresp_2eproto();

class CreateReq;

// ===================================================================

class CreateReq : public ::google::protobuf::Message {
 public:
  CreateReq();
  virtual ~CreateReq();

  CreateReq(const CreateReq& from);

  inline CreateReq& operator=(const CreateReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateReq& default_instance();

  void Swap(CreateReq* other);

  // implements Message ----------------------------------------------

  CreateReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CreateReq& from);
  void MergeFrom(const CreateReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 magic = 1;
  inline bool has_magic() const;
  inline void clear_magic();
  static const int kMagicFieldNumber = 1;
  inline ::google::protobuf::uint32 magic() const;
  inline void set_magic(::google::protobuf::uint32 value);

  // required uint32 op = 2;
  inline bool has_op() const;
  inline void clear_op();
  static const int kOpFieldNumber = 2;
  inline ::google::protobuf::uint32 op() const;
  inline void set_op(::google::protobuf::uint32 value);

  // required uint32 opsn = 3;
  inline bool has_opsn() const;
  inline void clear_opsn();
  static const int kOpsnFieldNumber = 3;
  inline ::google::protobuf::uint32 opsn() const;
  inline void set_opsn(::google::protobuf::uint32 value);

  // required uint32 volume_id = 4;
  inline bool has_volume_id() const;
  inline void clear_volume_id();
  static const int kVolumeIdFieldNumber = 4;
  inline ::google::protobuf::uint32 volume_id() const;
  inline void set_volume_id(::google::protobuf::uint32 value);

  // required uint32 chunk_size = 5;
  inline bool has_chunk_size() const;
  inline void clear_chunk_size();
  static const int kChunkSizeFieldNumber = 5;
  inline ::google::protobuf::uint32 chunk_size() const;
  inline void set_chunk_size(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:reqresp.CreateReq)
 private:
  inline void set_has_magic();
  inline void clear_has_magic();
  inline void set_has_op();
  inline void clear_has_op();
  inline void set_has_opsn();
  inline void clear_has_opsn();
  inline void set_has_volume_id();
  inline void clear_has_volume_id();
  inline void set_has_chunk_size();
  inline void clear_has_chunk_size();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 magic_;
  ::google::protobuf::uint32 op_;
  ::google::protobuf::uint32 opsn_;
  ::google::protobuf::uint32 volume_id_;
  ::google::protobuf::uint32 chunk_size_;
  friend void  protobuf_AddDesc_reqresp_2eproto();
  friend void protobuf_AssignDesc_reqresp_2eproto();
  friend void protobuf_ShutdownFile_reqresp_2eproto();

  void InitAsDefaultInstance();
  static CreateReq* default_instance_;
};
// ===================================================================


// ===================================================================

// CreateReq

// required uint32 magic = 1;
inline bool CreateReq::has_magic() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CreateReq::set_has_magic() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CreateReq::clear_has_magic() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CreateReq::clear_magic() {
  magic_ = 0u;
  clear_has_magic();
}
inline ::google::protobuf::uint32 CreateReq::magic() const {
  // @@protoc_insertion_point(field_get:reqresp.CreateReq.magic)
  return magic_;
}
inline void CreateReq::set_magic(::google::protobuf::uint32 value) {
  set_has_magic();
  magic_ = value;
  // @@protoc_insertion_point(field_set:reqresp.CreateReq.magic)
}

// required uint32 op = 2;
inline bool CreateReq::has_op() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CreateReq::set_has_op() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CreateReq::clear_has_op() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CreateReq::clear_op() {
  op_ = 0u;
  clear_has_op();
}
inline ::google::protobuf::uint32 CreateReq::op() const {
  // @@protoc_insertion_point(field_get:reqresp.CreateReq.op)
  return op_;
}
inline void CreateReq::set_op(::google::protobuf::uint32 value) {
  set_has_op();
  op_ = value;
  // @@protoc_insertion_point(field_set:reqresp.CreateReq.op)
}

// required uint32 opsn = 3;
inline bool CreateReq::has_opsn() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CreateReq::set_has_opsn() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CreateReq::clear_has_opsn() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CreateReq::clear_opsn() {
  opsn_ = 0u;
  clear_has_opsn();
}
inline ::google::protobuf::uint32 CreateReq::opsn() const {
  // @@protoc_insertion_point(field_get:reqresp.CreateReq.opsn)
  return opsn_;
}
inline void CreateReq::set_opsn(::google::protobuf::uint32 value) {
  set_has_opsn();
  opsn_ = value;
  // @@protoc_insertion_point(field_set:reqresp.CreateReq.opsn)
}

// required uint32 volume_id = 4;
inline bool CreateReq::has_volume_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CreateReq::set_has_volume_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CreateReq::clear_has_volume_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CreateReq::clear_volume_id() {
  volume_id_ = 0u;
  clear_has_volume_id();
}
inline ::google::protobuf::uint32 CreateReq::volume_id() const {
  // @@protoc_insertion_point(field_get:reqresp.CreateReq.volume_id)
  return volume_id_;
}
inline void CreateReq::set_volume_id(::google::protobuf::uint32 value) {
  set_has_volume_id();
  volume_id_ = value;
  // @@protoc_insertion_point(field_set:reqresp.CreateReq.volume_id)
}

// required uint32 chunk_size = 5;
inline bool CreateReq::has_chunk_size() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CreateReq::set_has_chunk_size() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CreateReq::clear_has_chunk_size() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CreateReq::clear_chunk_size() {
  chunk_size_ = 0u;
  clear_has_chunk_size();
}
inline ::google::protobuf::uint32 CreateReq::chunk_size() const {
  // @@protoc_insertion_point(field_get:reqresp.CreateReq.chunk_size)
  return chunk_size_;
}
inline void CreateReq::set_chunk_size(::google::protobuf::uint32 value) {
  set_has_chunk_size();
  chunk_size_ = value;
  // @@protoc_insertion_point(field_set:reqresp.CreateReq.chunk_size)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace reqresp

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_reqresp_2eproto__INCLUDED
